# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package to npmjs
on:
  push:
    branches:
      - 'main'
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
      FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
      - name: Set Outputs major version
        id: set-outputs-major
        run: echo "MajorMinorPatch=${{ steps.gitversion.outputs.majorMinorPatch }}" >> $GITHUB_OUTPUT
      - name: Set Outputs full version
        id: set-outputs-full
        run: echo "FullSemVer=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: [calculate-version]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - run: yarn version --new-version "${{ needs.calculate-version.outputs.MajorMinorPatch }}" --no-git-tag-version
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}